name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'container/**'

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build

      - name: setting1
        run: echo 'AWS_S3_BUCKET_NAME=secrets.AWS_S3_BUCKET_NAME' >> $GITHUB_ENV

      - name: setting2
        run: echo 'AWS_ACCESS_KEY_ID=secrets.AWS_ACCESS_KEY_ID' >> $GITHUB_ENV

      - name: setting3
        run: echo 'AWS_SECRET_ACCESS_KEY=secrets.AWS_SECRET_ACCESS_KEY' >> $GITHUB_ENV

      - uses: chrislennon/action-aws-cli@v1.1

      - run: aws s3 sync dist s3://${{ AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}